### ISSUE TITLE
Where is "DAUNet.hdf5"

### ISSUE THREAD

**Issue by i-spoon** [dvalex/daunet#1]
I want to fork it in my computer ,but i dont find the file named "DAUNet.hdf5".Could you can give me a link to download it.I will be grateful if you can give me a hand.

**Comment by dvalex** [comment]
It was renamed to [DAUNet-finetuned.hdf5](https://github.com/dvalex/daunet/blob/main/model2/DAUNet-finetuned.hdf5)
