### ISSUE TITLE
The crack500.zip download link is not working.

### ISSUE THREAD

**Issue by Weikido** [dvalex/daunet#2]
I want to fork it in my computer, but the crack500.zip download link shows "Sorry, the file you requested does not exist."
Can you update the download link, please?

<img width="529" alt="Snipaste_2022-07-06_18-42-09" src="https://user-images.githubusercontent.com/42232758/177532700-53ebdef4-9d2d-4b56-9018-2ff61d50a74a.png">

**Comment by dvalex** [comment]
The broken link has been fixed

**Comment by Weikido** [comment]
Thank you, I have requested access to crack500.zip from you.
